import { format } from "date-fns";
import { notFound } from "next/navigation";
import { RefreshCw } from "lucide-react";
import { AppShell } from "@/components/dashboard/app-shell";
import { StatCard } from "@/components/dashboard/stat-card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { getWorkspaceMembers } from "@/lib/services/workspace-service";
import { getLinkedInDashboardData, linkedinConnectors, linkedinMemberRoles } from "@/modules/linkedin-assessor";
import { requireLinkedInAdmin } from "@/modules/linkedin-assessor/context";
import { setTrackedMemberStatusAction, syncLinkedInAction, updateTrackedMemberAction } from "../../../actions";

export default async function LinkedInMemberDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const { supabase, workspace } = await requireLinkedInAdmin();
  const [data, workspaceMembers] = await Promise.all([getLinkedInDashboardData(supabase, workspace.id, { includeLogs: true }), getWorkspaceMembers(supabase, workspace.id)]);
  const member = data.stats.find((item) => item.trackedMemberId === id);
  const trackedMember = data.members.find((item) => item.id === id);
  if (!member || !trackedMember) notFound();
  const posts = data.posts.filter((post) => post.memberId === id);
  return <AppShell>
    <div className="mb-6 flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex flex-wrap items-center gap-2"><h1 className="text-3xl font-semibold">{member.name}</h1><Badge>{member.trackingStatus.replaceAll("_", " ")}</Badge></div><a href={member.linkedinProfileUrl} target="_blank" rel="noreferrer" className="text-sm text-muted-foreground hover:underline">{member.linkedinProfileUrl}</a></div><div className="flex flex-wrap gap-2"><form action={syncLinkedInAction}><input type="hidden" name="memberId" value={id} /><Button variant="outline"><RefreshCw className="h-4 w-4" />Sync profile</Button></form><form action={setTrackedMemberStatusAction}><input type="hidden" name="memberId" value={id} /><input type="hidden" name="status" value={member.trackingStatus === "paused" ? "pending" : "paused"} /><Button variant="outline">{member.trackingStatus === "paused" ? "Resume" : "Pause"}</Button></form></div></div>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard title="Posts" value={member.postCount} /><StatCard title="Volume score" value={member.volumeScore} /><StatCard title="Average quality" value={member.averageQualityScore ?? "N/A"} /><StatCard title="Final score" value={member.finalScore ?? "N/A"} /></div>
    <div className="mt-6 grid gap-4 lg:grid-cols-2"><SignalCard title="Top strengths" items={member.topStrengths} /><SignalCard title="Improvement focus" items={member.improvementFocus} /></div>
    <Card className="mt-6"><CardHeader><CardTitle>Edit tracked profile</CardTitle></CardHeader><CardContent><form action={updateTrackedMemberAction} className="grid gap-4 sm:grid-cols-2"><input type="hidden" name="memberId" value={id} /><Field label="Name" name="name" defaultValue={trackedMember.name} /><Field label="Email" name="email" type="email" defaultValue={trackedMember.email ?? ""} /><div className="space-y-2 sm:col-span-2"><Label htmlFor="profileId">Toolkit account</Label><select id="profileId" name="profileId" defaultValue={trackedMember.profile_id ?? ""} className="h-10 w-full rounded-md border border-border bg-card px-3 text-sm"><option value="">Not linked</option>{workspaceMembers.map((item) => <option key={item.user_id} value={item.user_id}>{item.profiles?.full_name ?? item.profiles?.email}</option>)}</select></div><div className="space-y-2"><Label htmlFor="memberRole">Role</Label><select id="memberRole" name="memberRole" defaultValue={trackedMember.member_role} className="h-10 w-full rounded-md border border-border bg-card px-3 text-sm">{linkedinMemberRoles.map((role) => <option key={role} value={role}>{role.replaceAll("_", " ")}</option>)}</select></div><div className="space-y-2"><Label htmlFor="connectorPreference">Connector</Label><select id="connectorPreference" name="connectorPreference" defaultValue={trackedMember.connector_preference} className="h-10 w-full rounded-md border border-border bg-card px-3 text-sm">{linkedinConnectors.map((connector) => <option key={connector} value={connector}>{connector.replaceAll("_", " ")}</option>)}</select></div><Field className="sm:col-span-2" label="LinkedIn profile URL" name="linkedinProfileUrl" defaultValue={trackedMember.linkedin_profile_url} /><Field label="Monthly post target" name="monthlyPostTarget" type="number" min="1" max="100" defaultValue={trackedMember.monthly_post_target} /><div /><Field label="Volume weight" name="volumeWeight" type="number" min="0" max="1" step="0.05" defaultValue={trackedMember.volume_weight} /><Field label="Quality weight" name="qualityWeight" type="number" min="0" max="1" step="0.05" defaultValue={trackedMember.quality_weight} /><div className="sm:col-span-2"><Button>Save profile</Button></div></form><form action={setTrackedMemberStatusAction} className="mt-4 border-t border-border pt-4"><input type="hidden" name="memberId" value={id} /><input type="hidden" name="status" value="archived" /><Button variant="outline">Archive profile</Button></form></CardContent></Card>
    <Card className="mt-6"><CardHeader><CardTitle>Recent assessed posts</CardTitle></CardHeader><CardContent className="space-y-4">{posts.map((post) => <article key={post.id} className="border-b border-border pb-4 last:border-0 last:pb-0"><div className="flex flex-wrap items-center justify-between gap-2 text-sm"><span className="text-muted-foreground">{format(new Date(post.postedAt), "MMM d, yyyy")}</span><div className="flex flex-wrap gap-2">{post.id === member.bestPostId ? <Badge>Best post</Badge> : null}{post.id === member.weakestPostId ? <Badge>Needs focus</Badge> : null}<Badge>{post.postKind.replaceAll("_", " ")}</Badge><Badge>{post.archetype.replaceAll("_", " ")}</Badge><Badge>{post.score ?? "Unscored"}</Badge></div></div><p className="mt-2 text-sm leading-6">{post.text}</p>{post.summary ? <p className="mt-2 text-sm text-muted-foreground">{post.summary}</p> : null}</article>)}{posts.length === 0 ? <p className="text-sm text-muted-foreground">No assessed posts have been collected in this analysis window.</p> : null}</CardContent></Card>
    <Card className="mt-6"><CardHeader><CardTitle>Sync history</CardTitle></CardHeader><CardContent className="space-y-3">{data.logs.filter((log) => log.tracked_member_id === id).map((log) => <div key={log.id} className="border-b border-border pb-3 text-sm last:border-0"><div className="font-medium capitalize">{log.status} · {format(new Date(log.created_at), "MMM d, yyyy h:mm a")}</div><div className="text-muted-foreground">{log.message}</div></div>)}{data.logs.every((log) => log.tracked_member_id !== id) ? <p className="text-sm text-muted-foreground">No sync attempts recorded.</p> : null}</CardContent></Card>
  </AppShell>;
}

function SignalCard({ title, items }: { title: string; items: string[] }) { return <Card><CardHeader><CardTitle>{title}</CardTitle></CardHeader><CardContent><ul className="space-y-2 text-sm text-muted-foreground">{items.length ? items.map((item) => <li key={item}>{item}</li>) : <li>No scored signals yet.</li>}</ul></CardContent></Card>; }
function Field({ label, name, className, ...props }: { label: string; name: string; className?: string } & React.InputHTMLAttributes<HTMLInputElement>) { return <div className={`space-y-2 ${className ?? ""}`}><Label htmlFor={name}>{label}</Label><Input id={name} name={name} required {...props} /></div>; }
