import { FileBarChart } from "lucide-react";
import { AppShell } from "@/components/dashboard/app-shell";
import { SubmitButton } from "@/components/dashboard/submit-button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { getLinkedInDashboardData } from "@/modules/linkedin-assessor";
import { formatISTDate, formatISTDateTime, formatISTShortDate } from "@/lib/utils/dates";
import { requireLinkedInAdmin } from "@/modules/linkedin-assessor/context";
import { generateLinkedInReportAction } from "../actions";

export default async function LinkedInReportsPage() {
  const { supabase, workspace } = await requireLinkedInAdmin("/tools/linkedin-assessor/reports");
  const data = await getLinkedInDashboardData(supabase, workspace.id, { includeReports: true });
  return <AppShell><div className="mb-6 flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><h1 className="text-3xl font-semibold">LinkedIn Reports</h1><p className="text-muted-foreground">Fixed seven-day snapshots of manual submissions, quality, trends, and coaching focus.</p></div><form action={generateLinkedInReportAction}><SubmitButton><FileBarChart className="h-4 w-4" />Generate report</SubmitButton></form></div><div className="space-y-4">{data.reports.map((report) => { const payload = report.report_json as ReportPayload; return <Card key={report.id}><CardHeader><CardTitle>{formatISTShortDate(report.start_date)} - {formatISTDate(report.end_date)}</CardTitle><CardDescription>Generated {formatISTDateTime(report.created_at)}</CardDescription></CardHeader><CardContent><p className="text-sm leading-6 text-muted-foreground">{report.report_summary}</p>{payload?.summary ? <div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Posts" value={payload.summary.totalPosts} /><Metric label="Average quality" value={payload.summary.averageQuality ?? "N/A"} /><Metric label="Most active" value={payload.summary.mostActiveMember ?? "N/A"} /><Metric label="Highest quality" value={payload.summary.highestQualityMember ?? "N/A"} /></div> : null}{payload?.members?.length ? <details className="mt-4"><summary className="cursor-pointer text-sm font-medium">Member breakdown</summary><div className="mt-3 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b border-border"><th className="py-2">Member</th><th>Posts</th><th>Quality</th><th>Final</th><th>Trend</th></tr></thead><tbody>{payload.members.map((member) => <tr key={member.trackedMemberId} className="border-b border-border"><td className="py-2">{member.name}</td><td>{member.postCount}</td><td>{member.averageQualityScore ?? "N/A"}</td><td>{member.finalScore ?? "N/A"}</td><td className="capitalize">{member.trend.replaceAll("_", " ")}</td></tr>)}</tbody></table></div></details> : null}</CardContent></Card>; })}{data.reports.length === 0 ? <Card><CardHeader><CardTitle>No weekly reports yet</CardTitle><CardDescription>Generate the first report after members submit and score posts.</CardDescription></CardHeader></Card> : null}</div></AppShell>;
}

type ReportPayload = { summary?: { totalPosts: number; averageQuality: number | null; mostActiveMember: string | null; highestQualityMember: string | null }; members?: Array<{ trackedMemberId: string; name: string; postCount: number; averageQualityScore: number | null; finalScore: number | null; trend: string }> };
function Metric({ label, value }: { label: string; value: string | number }) { return <div className="rounded-md border border-border p-3"><div className="text-xs text-muted-foreground">{label}</div><div className="mt-1 font-semibold">{value}</div></div>; }
