import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import type { LinkedInMemberStats } from "@/modules/linkedin-assessor";

export function LinkedInMemberScoreBreakdown({ stats }: { stats: LinkedInMemberStats[] }) {
  return <section className="mt-6"><div className="mb-3"><h2 className="text-lg font-semibold">Member score breakdown</h2><p className="text-sm text-muted-foreground">The exact volume and quality inputs behind each final score.</p></div><div className="grid gap-4 xl:grid-cols-3">{stats.map((member) => <Card key={member.trackedMemberId}><CardHeader><div className="flex items-center justify-between gap-3"><CardTitle className="text-base">{member.name}</CardTitle><span className="text-xl font-semibold">{member.finalScore ?? "N/A"}</span></div></CardHeader><CardContent><div className="grid grid-cols-2 gap-2 text-sm"><Tile label="Posts" value={member.postCount} /><Tile label="Target" value={member.periodTarget} /><Tile label={`Volume · ${Math.round(member.volumeWeight * 100)}%`} value={member.volumeScore} /><Tile label={`Quality · ${Math.round(member.qualityWeight * 100)}%`} value={member.averageQualityScore ?? "N/A"} /></div><Signal title="Strengths" items={member.topStrengths} /><Signal title="Improve" items={member.improvementFocus} /></CardContent></Card>)}</div></section>;
}

function Tile({ label, value }: { label: string; value: string | number }) { return <div className="rounded-md border border-border p-3"><div className="text-xs text-muted-foreground">{label}</div><div className="mt-1 font-semibold">{value}</div></div>; }
function Signal({ title, items }: { title: string; items: string[] }) { return <div className="mt-4"><div className="text-xs font-medium uppercase text-muted-foreground">{title}</div><div className="mt-2 flex flex-wrap gap-2">{(items.length ? items : ["No signals yet"]).map((item) => <span key={item} className="rounded-md bg-muted px-2 py-1 text-xs">{item}</span>)}</div></div>; }
